version: "1.0"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - laravel

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8989:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel

    postgres:
        image: postgres:latest
        environment:
            POSTGRES_USER: ${DB_USERNAME:-user}
            POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
            POSTGRES_DB: ${DB_DATABASE:-simplified-banking}
        volumes:
            - ./.docker/postgres:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - laravel

    redis:
        image: redis:latest
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
